export const initialSeedDocuments = [
  // 1. Topic Clusters
  {
    _id: 'cluster-understanding-neurodiversity',
    _type: 'guideCluster',
    title: 'Understanding Neurodiversity',
    nepaliTitle: 'न्युरोडाइभर्सिटी बुझाइ तथा आधारभूत स्रोतहरू',
    slug: { _type: 'slug', current: 'understanding-neurodiversity' },
    order: 1,
    badge: 'Foundational Frameworks',
    nepaliBadge: 'आधारभूत स्रोत',
    description: 'Core definitions, practical frameworks, and the low-to-high tech assistive spectrum for diverse learners.',
    nepaliDescription: 'न्युरोडाइभर्सिटीको आधुनिक अवधारणा र सहयोगी प्रविधिका आधारभूत पक्षहरू।',
    color: 'indigo',
    iconName: 'Compass',
  },
  {
    _id: 'cluster-autism-spectrum-disorder',
    _type: 'guideCluster',
    title: 'Autism Spectrum Disorder (ASD)',
    nepaliTitle: 'अटिजम स्पेक्ट्रम डिसअर्डर (कार्यकारी क्षमता र बोली)',
    slug: { _type: 'slug', current: 'autism-spectrum-disorder' },
    order: 2,
    badge: 'Executive Function & Speech',
    nepaliBadge: 'कार्यकारी क्षमता र बोली',
    description: 'Visual structure, emotional regulation, interoception, and AAC color-coding for autistic learners.',
    nepaliDescription: 'कार्यकारी क्षमता सहजीकरण, दृश्य संरचना, भावना व्यवस्थापन र एएसी रङ-संकेत प्रणाली।',
    color: 'emerald',
    iconName: 'Brain',
  },
  {
    _id: 'cluster-down-syndrome',
    _type: 'guideCluster',
    title: 'Down Syndrome (Trisomy 21 & Motor-Speech Scaffolding)',
    nepaliTitle: 'डाउन सिन्ड्रोम (ट्राइसोमी २१ तथा मांसपेशी-बोली सहजीकरण)',
    slug: { _type: 'slug', current: 'down-syndrome' },
    order: 3,
    badge: 'Hypotonia & Speech Scaffolding',
    nepaliBadge: 'मांसपेशी र बोली सहजीकरण',
    description: 'Evidence-informed interventions addressing hypotonia, visual scaffolding for auditory memory, and total communication speech aids.',
    nepaliDescription: 'डाउन सिन्ड्रोम भएका बालबालिकाका लागि मांसपेशी थकान कम गर्ने, सुन्ने स्मरणको विकल्प र समग्र सञ्चार।',
    color: 'sky',
    iconName: 'Sparkles',
  },
  {
    _id: 'cluster-intellectual-disabilities',
    _type: 'guideCluster',
    title: 'Intellectual Disabilities (ID & Adaptive Behavior)',
    nepaliTitle: 'बौद्धिक अपाङ्गता (दैनिक जीवन तथा अनुकूलन सीप)',
    slug: { _type: 'slug', current: 'intellectual-disabilities' },
    order: 4,
    badge: 'Adaptive Living & Functional Skills',
    nepaliBadge: 'दैनिक जीवन र व्यावहारिक सीप',
    description: 'Multi-sensory flashcards, step-by-step ADL sequencing, and concrete math and literacy tools for cognitive scaffolding.',
    nepaliDescription: 'बहु-संवेदी फ्ल्यासकार्ड, दैनिक क्रियाकलापको चरणबद्ध सिकाइ र व्यावहारिक शैक्षिक सीपहरू।',
    color: 'amber',
    iconName: 'Shapes',
  },
  {
    _id: 'cluster-cerebral-palsy',
    _type: 'guideCluster',
    title: 'Cerebral Palsy (CP) & Motor-Speech Intersection',
    nepaliTitle: 'सेरेब्रल पाल्सी (शारीरिक तथा बोली समन्वय)',
    slug: { _type: 'slug', current: 'cerebral-palsy' },
    order: 5,
    badge: 'Motor-Speech & CP Access',
    nepaliBadge: 'शारीरिक तथा बोली पहुँच',
    description: 'Motor incoordination, speech apraxia, high-contrast large-target interfaces, and single-tap vs. complex AAC systems.',
    nepaliDescription: 'शारीरिक चालको असन्तुलन, उच्च-कन्ट्रास्ट ठूला बटनहरू र द्रुत सञ्चार प्रणाली।',
    color: 'violet',
    iconName: 'Activity',
  },

  // 2. Educational Guides (14 Guides)
  {
    _id: 'guide-what-does-neurodivergent-mean',
    _type: 'guide',
    title: 'What Does It Mean to Be Neurodivergent? A Modern Educational Perspective',
    nepaliTitle: 'न्युरोडाइभर्सिटी भनेको के हो? आधुनिक शैक्षिक परिप्रेक्ष्य',
    slug: { _type: 'slug', current: 'what-does-neurodivergent-mean' },
    cluster: { _type: 'reference', _ref: 'cluster-understanding-neurodiversity' },
    isPrimary: true,
    order: 1,
    status: 'published',
    readingTime: '10 min read',
    nepaliReadingTime: '१० मिनेट पढाइ',
    excerpt: 'Explore the modern definition of neurodiversity across autism, ADHD, dyslexia, and developmental variations through a strength-based educational lens.',
    nepaliExcerpt: 'अटिजम, एडीएचडी र सिकाइ भिन्नताको आधुनिक शक्ति-केन्द्रित शैक्षिक बुझाइ।',
    primaryKeyword: 'what does neurodivergent mean',
    secondaryKeywords: ['neurodiversity strengths', 'educational accommodations', 'sensory processing differences'],
  },
  {
    _id: 'guide-assistive-technology-in-special-education',
    _type: 'guide',
    title: 'Assistive Technology (AT) in Special Education: Removing Cognitive and Physical Barriers',
    nepaliTitle: 'विशेष शिक्षामा सहयोगी प्रविधि: संज्ञानात्मक र शारीरिक बाधाहरू हटाउने उपाय',
    slug: { _type: 'slug', current: 'assistive-technology-in-special-education' },
    cluster: { _type: 'reference', _ref: 'cluster-understanding-neurodiversity' },
    isPrimary: false,
    order: 2,
    status: 'published',
    readingTime: '12 min read',
    nepaliReadingTime: '१२ मिनेट पढाइ',
    excerpt: 'A comprehensive framework on selecting and implementing assistive technology in classrooms, home programs, and community settings.',
    nepaliExcerpt: 'कक्षाकोठा र घरमा सहयोगी प्रविधि छनोट र प्रयोग गर्ने पूर्ण रूपरेखा।',
    primaryKeyword: 'assistive technology special education',
    secondaryKeywords: ['IEP accommodations', 'universal design for learning', 'adaptive education tools'],
  },
  {
    _id: 'guide-low-tech-vs-high-tech-assistive-technology',
    _type: 'guide',
    title: 'Low-Tech vs. Mid-Tech vs. High-Tech: Navigating the AT Spectrum for Diverse Learners',
    nepaliTitle: 'लो-टेक बनाम हाई-टेक: विविध सिकारुहरूका लागि सहयोगी प्रविधि स्पेक्ट्रम',
    slug: { _type: 'slug', current: 'low-tech-vs-high-tech-assistive-technology' },
    cluster: { _type: 'reference', _ref: 'cluster-understanding-neurodiversity' },
    isPrimary: false,
    order: 3,
    status: 'published',
    readingTime: '11 min read',
    nepaliReadingTime: '११ मिनेट पढाइ',
    excerpt: 'Learn how to balance paper-based communication boards, battery-operated voice output aids, and dynamic tablet-based applications.',
    nepaliExcerpt: 'कागजी सञ्चार बोर्ड, ब्याट्रीबाट चल्ने उपकरण र ट्याबलेट एपहरूबीचको सन्तुलन।',
    primaryKeyword: 'low tech vs high tech assistive technology',
    secondaryKeywords: ['AAC continuum', 'assistive tech evaluation', 'cost-effective learning aids'],
  },

  {
    _id: 'guide-visual-structure-and-task-analysis-autism',
    _type: 'guide',
    title: 'Visual Structure & Task Analysis: Mitigating Executive Dysfunction in Autism',
    nepaliTitle: 'दृश्य संरचना र कार्य विश्लेषण: अटिजममा कार्यकारी क्षमताको सहजीकरण',
    slug: { _type: 'slug', current: 'visual-structure-and-task-analysis-autism' },
    cluster: { _type: 'reference', _ref: 'cluster-autism-spectrum-disorder' },
    isPrimary: true,
    order: 1,
    status: 'published',
    readingTime: '14 min read',
    nepaliReadingTime: '१४ मिनेट पढाइ',
    excerpt: 'Step-by-step guidance on breaking down multi-step routines, mitigating executive dysfunction, and using visual cues to support autonomy.',
    nepaliExcerpt: 'जटिल कामहरूलाई साना-साना चरणहरूमा विभाजन गरी स्वावलम्बी बनाउने दृश्य विधि।',
    primaryKeyword: 'visual structure task analysis autism',
    secondaryKeywords: ['executive dysfunction strategies', 'visual schedules', 'TEACCH structured teaching'],
  },
  {
    _id: 'guide-interoception-and-alexithymia-autism',
    _type: 'guide',
    title: 'Interoception, Alexithymia, and Emotional Regulation Tools for Autistic Learners',
    nepaliTitle: 'इन्ट्रोसेप्शन, एलेक्सिथिमिया र अटिजम भएका बालबालिकाका लागि भावना नियमन',
    slug: { _type: 'slug', current: 'interoception-and-alexithymia-autism' },
    cluster: { _type: 'reference', _ref: 'cluster-autism-spectrum-disorder' },
    isPrimary: false,
    order: 2,
    status: 'published',
    readingTime: '13 min read',
    nepaliReadingTime: '१३ मिनेट पढाइ',
    excerpt: 'Understanding internal bodily signals, identifying emotional states, and building digital tools that support interoceptive awareness.',
    nepaliExcerpt: 'आफ्नो शरीरको संकेत बुझ्ने, भावना पहिचान गर्ने र डिजिटल उपकरणको प्रयोग।',
    primaryKeyword: 'interoception alexithymia autism',
    secondaryKeywords: ['emotional regulation apps', 'sensory body maps', 'autistic self-regulation'],
  },
  {
    _id: 'guide-aac-fitzgerald-key-color-coding',
    _type: 'guide',
    title: 'AAC & Fitzgerald Key Color-Coding: Supporting Non-Verbal and Gestural Communicators',
    nepaliTitle: 'एएसी र फिट्जगेराल्ड रङ-संकेत: गैर-मौखिक सञ्चारकर्ताहरूको लागि सहयोग',
    slug: { _type: 'slug', current: 'aac-fitzgerald-key-color-coding' },
    cluster: { _type: 'reference', _ref: 'cluster-autism-spectrum-disorder' },
    isPrimary: false,
    order: 3,
    status: 'published',
    readingTime: '15 min read',
    nepaliReadingTime: '१५ मिनेट पढाइ',
    excerpt: 'How standardized grammatical color-coding organizes vocabulary grids and accelerates sentence building for non-speaking communicators.',
    nepaliExcerpt: 'व्याकरणिक रङ प्रणालीमार्फत शब्द भण्डार व्यवस्थित गर्ने र वाक्य निर्माण सिकाउने।',
    primaryKeyword: 'AAC Fitzgerald Key color coding',
    secondaryKeywords: ['augmentative communication', 'visual syntax', 'core vocabulary boards'],
  },

  {
    _id: 'guide-assistive-tech-for-down-syndrome',
    _type: 'guide',
    title: 'Assistive Tech for Down Syndrome: Addressing Hypotonia, Fine-Motor Fatigue, and Speech Apraxia',
    nepaliTitle: 'डाउन सिन्ड्रोमका लागि सहयोगी प्रविधि: मांसपेशी कमजोरी, थकान र बोली सहजीकरण',
    slug: { _type: 'slug', current: 'assistive-tech-for-down-syndrome' },
    cluster: { _type: 'reference', _ref: 'cluster-down-syndrome' },
    isPrimary: true,
    order: 1,
    status: 'published',
    readingTime: '13 min read',
    nepaliReadingTime: '१३ मिनेट पढाइ',
    excerpt: 'Practical assistive technologies designed for low muscle tone, joint hypermobility, motor fatigue, and speech articulation barriers.',
    nepaliExcerpt: 'मांसपेशीको कमजोरी र बोली स्पष्टताका लागि बनाइएका व्यावहारिक सहयोगी प्रविधिहरू।',
    primaryKeyword: 'assistive tech for Down syndrome',
    secondaryKeywords: ['hypotonia touchscreen adaptations', 'speech apraxia apps', 'Trisomy 21 fine motor'],
  },
  {
    _id: 'guide-visual-scaffolding-auditory-memory-down-syndrome',
    _type: 'guide',
    title: 'Visual Scaffolding for Auditory Memory Deficits in Down Syndrome Learners',
    nepaliTitle: 'डाउन सिन्ड्रोममा श्रव्य स्मरणको विकल्प: दृश्य सहजीकरण विधि',
    slug: { _type: 'slug', current: 'visual-scaffolding-auditory-memory-down-syndrome' },
    cluster: { _type: 'reference', _ref: 'cluster-down-syndrome' },
    isPrimary: false,
    order: 2,
    status: 'published',
    readingTime: '14 min read',
    nepaliReadingTime: '१४ मिनेट पढाइ',
    excerpt: 'How visual anchor systems bypass phonological loop working memory bottlenecks in Down syndrome education.',
    nepaliExcerpt: 'सुनेर सम्झन गाह्रो हुने अवस्थामा चित्र र दृश्य तालिकाको मद्दतले सिकाउने तरिका।',
    primaryKeyword: 'visual scaffolding auditory memory Down syndrome',
    secondaryKeywords: ['working memory adaptations', 'visual strength learning', 'bilingual speech cues'],
  },
  {
    _id: 'guide-total-communication-mid-tech-speech-aids',
    _type: 'guide',
    title: 'Total Communication & Mid-Tech Speech Aids: Bridging Receptive and Expressive Gaps',
    nepaliTitle: 'समग्र सञ्चार र मिड-टेक बोली उपकरणहरू: बुझाइ र अभिव्यक्तिको दूरी घटाउने उपाय',
    slug: { _type: 'slug', current: 'total-communication-mid-tech-speech-aids' },
    cluster: { _type: 'reference', _ref: 'cluster-down-syndrome' },
    isPrimary: false,
    order: 3,
    status: 'published',
    readingTime: '12 min read',
    nepaliReadingTime: '१२ मिनेट पढाइ',
    excerpt: 'Combining gestures, signs, tactile boards, and digital voice output aids into a unified total communication framework.',
    nepaliExcerpt: 'इशारा, संकेत, र आवाज निकाल्ने यन्त्रहरूको संयुक्त प्रयोगमार्फत सञ्चार।',
    primaryKeyword: 'total communication mid-tech speech aids',
    secondaryKeywords: ['multi-modal communication', 'receptive expressive gap', 'speech generating devices'],
  },

  {
    _id: 'guide-cognitive-accessibility-digital-flashcards',
    _type: 'guide',
    title: 'Cognitive Accessibility: Designing Multi-Sensory Digital Flashcards & Vocabulary Aids',
    nepaliTitle: 'संज्ञानात्मक पहुँच: बहु-संवेदी डिजिटल फ्ल्यासकार्ड र शब्दावली साधन',
    slug: { _type: 'slug', current: 'cognitive-accessibility-digital-flashcards' },
    cluster: { _type: 'reference', _ref: 'cluster-intellectual-disabilities' },
    isPrimary: true,
    order: 1,
    status: 'published',
    readingTime: '12 min read',
    nepaliReadingTime: '१२ मिनेट पढाइ',
    excerpt: 'Design cognitively accessible digital flashcards and vocabulary aids with multi-sensory feedback, uncluttered layouts, and high readability.',
    nepaliExcerpt: 'सफा लेआउट र आवाज सहितका बहु-संवेदी डिजिटल फ्ल्यासकार्ड बनाउने उपाय।',
    primaryKeyword: 'cognitive accessibility digital flashcards',
    secondaryKeywords: ['multi-sensory flashcards', 'accessible vocabulary tools', 'intellectual disability tech'],
  },
  {
    _id: 'guide-task-analysis-home-executive-dysfunction',
    _type: 'guide',
    title: 'Daily Living Skills (ADLs): Step-by-Step Task Sequencing for Independent Living',
    nepaliTitle: 'दैनिक जीवनका सीपहरू (ADLs): आत्मनिर्भरताका लागि चरणबद्ध कार्य योजना',
    slug: { _type: 'slug', current: 'task-analysis-home-executive-dysfunction' },
    cluster: { _type: 'reference', _ref: 'cluster-intellectual-disabilities' },
    isPrimary: false,
    order: 2,
    status: 'published',
    readingTime: '11 min read',
    nepaliReadingTime: '११ मिनेट पढाइ',
    excerpt: 'A practical guide on breaking down complex daily self-care routines into manageable steps with visual checkpoints.',
    nepaliExcerpt: 'दैनिक सरसफाइ र आत्मनिर्भरताका कामहरू सजिलै सिकाउने दृश्य जाँचसूची।',
    primaryKeyword: 'daily living skills task sequencing ADL',
    secondaryKeywords: ['ADL task analysis', 'independent living aids', 'visual routine checklists'],
  },
  {
    _id: 'guide-functional-academics-special-education',
    _type: 'guide',
    title: 'Functional Academics: Concrete Math and Literacy Tools for Cognitive Scaffolding',
    nepaliTitle: 'व्यावहारिक शिक्षा: ठोस गणित र साक्षरता उपकरणहरू',
    slug: { _type: 'slug', current: 'functional-academics-special-education' },
    cluster: { _type: 'reference', _ref: 'cluster-intellectual-disabilities' },
    isPrimary: false,
    order: 3,
    status: 'published',
    readingTime: '13 min read',
    nepaliReadingTime: '१३ मिनेट पढाइ',
    excerpt: 'Master functional academics for ID, Down syndrome, and CP with money math, real-world sight words, and concrete digital scaffolds.',
    nepaliExcerpt: 'दैनिक जीवनमा काम लाग्ने पैसाको हिसाब र व्यावहारिक शब्दहरू सिकाउने विधि।',
    primaryKeyword: 'functional academics concrete math literacy',
    secondaryKeywords: ['concrete math manipulatives', 'functional literacy ID', 'real-world life math'],
  },

  {
    _id: 'guide-adaptive-tech-for-cerebral-palsy',
    _type: 'guide',
    title: 'Adaptive Tech for Cerebral Palsy: Navigating Fine Motor Incoordination and Speech Apraxia',
    nepaliTitle: 'सेरेब्रल पाल्सीका लागि अनुकूलित प्रविधि: शारीरिक असन्तुलन र बोली सहजीकरण',
    slug: { _type: 'slug', current: 'adaptive-tech-for-cerebral-palsy' },
    cluster: { _type: 'reference', _ref: 'cluster-cerebral-palsy' },
    isPrimary: true,
    order: 1,
    status: 'published',
    readingTime: '14 min read',
    nepaliReadingTime: '१४ मिनेट पढाइ',
    excerpt: 'An engineered ecosystem of physical, communicative, and digital tools designed to bypass neuromuscular motor impairments without cognitive overload.',
    nepaliExcerpt: 'शारीरिक चालको असन्तुलन र कम्पन भएका बालबालिकाका लागि अनुकूलित प्रविधि।',
    primaryKeyword: 'adaptive tech for cerebral palsy',
    secondaryKeywords: ['fine motor incoordination', 'speech apraxia aids', 'CP switch access'],
  },
  {
    _id: 'guide-high-contrast-large-target-interfaces',
    _type: 'guide',
    title: 'High-Contrast & Large-Target Digital Interfaces for Motor Impairments',
    nepaliTitle: 'उच्च-कन्ट्रास्ट तथा ठूला-बटन डिजिटल इन्टरफेस: शारीरिक अशक्तताका लागि डिजाइन',
    slug: { _type: 'slug', current: 'high-contrast-large-target-interfaces' },
    cluster: { _type: 'reference', _ref: 'cluster-cerebral-palsy' },
    isPrimary: false,
    order: 2,
    status: 'published',
    readingTime: '13 min read',
    nepaliReadingTime: '१३ मिनेट पढाइ',
    excerpt: 'Specialized assistive technology UI/UX configurations engineered to reduce visual fatigue and accommodate involuntary physical movements.',
    nepaliExcerpt: 'अनियन्त्रित चाल भएका व्यक्तिहरूका लागि आँखा नथाक्ने उच्च-कन्ट्रास्ट ठूला बटनहरू।',
    primaryKeyword: 'high contrast large target digital interfaces',
    secondaryKeywords: ['motor impairment accessibility', 'large touch targets', 'tremor filtration UX'],
  },
  {
    _id: 'guide-single-tap-vs-complex-aac-dual-barriers',
    _type: 'guide',
    title: 'Single-Tap Quick Talkers vs. Complex AAC for Dual Motor-Speech Barriers',
    nepaliTitle: 'एकल-ट्याप द्रुत टकर बनाम जटिल एएसी: दोहोरो शारीरिक र बोली अवरोधको समाधान',
    slug: { _type: 'slug', current: 'single-tap-vs-complex-aac-dual-barriers' },
    cluster: { _type: 'reference', _ref: 'cluster-cerebral-palsy' },
    isPrimary: false,
    order: 3,
    status: 'published',
    readingTime: '14 min read',
    nepaliReadingTime: '१४ मिनेट पढाइ',
    excerpt: 'Balancing communicative speed against linguistic depth for learners navigating simultaneous physical motor barriers and speech apraxia.',
    nepaliExcerpt: 'दोहोरो शारीरिक र बोली अवरोध भएका सिकारुहरूका लागि तत्काल चाहिने कुरा बोल्ने उपाय।',
    primaryKeyword: 'single tap quick talkers vs complex AAC',
    secondaryKeywords: ['dual motor speech barriers', 'emergency quick talkers', 'dynamic display AAC'],
  },

  // 3. Supportive Web-Apps (8 tools)
  {
    _id: 'app-talker-aac',
    _type: 'supportiveWebApp',
    title: 'Quick-Tap Talker AAC',
    nepaliTitle: 'द्रुत टकर एएसी',
    slug: { _type: 'slug', current: 'talker-aac' },
    order: 1,
    category: 'AAC & Communication',
    nepaliCategory: 'सञ्चार तथा अभिव्यक्ति',
    ageRange: 'Ages 3–12+',
    nepaliAgeRange: '३–१२+ वर्ष',
    flutterRoute: '/talker-aac',
    shortDescription: 'High-contrast, direct-selection communication grid with synthesized voice output for emergency requests and essential needs.',
    nepaliShortDescription: 'अत्यावश्यक कुराहरू तत्काल व्यक्त गर्न सकिने ठूला र स्पष्ट बटन भएको आवाज निकाल्ने सञ्चार ग्रिड।',
    sensoryAccommodations: 'No background audio clutter; vibration feedback on tap; high contrast color mode.',
  },
  {
    _id: 'app-sentence-builder',
    _type: 'supportiveWebApp',
    title: 'Fitzgerald Key Sentence Builder',
    nepaliTitle: 'वाक्य निर्माण तथा व्याकरण ग्रिड',
    slug: { _type: 'slug', current: 'sentence-builder' },
    order: 2,
    category: 'AAC & Communication',
    nepaliCategory: 'सञ्चार तथा अभिव्यक्ति',
    ageRange: 'Ages 5–16+',
    nepaliAgeRange: '५–१६+ वर्ष',
    flutterRoute: '/sentence-builder',
    shortDescription: 'Visual sentence construction workspace color-coded using the modified Fitzgerald Key system for bilingual communication.',
    nepaliShortDescription: 'फिट्जगेराल्ड रङ प्रणालीमा आधारित वाक्य बनाउने अभ्यास जसले बालबालिकालाई पूर्ण वाक्य बोल्न सिकाउँछ।',
  },
  {
    _id: 'app-emotion-regulation',
    _type: 'supportiveWebApp',
    title: 'Visual Emotion Regulation Board',
    nepaliTitle: 'भावना नियमन तथा शान्त बोर्ड',
    slug: { _type: 'slug', current: 'emotion-regulation' },
    order: 3,
    category: 'Sensory & Self-Regulation',
    nepaliCategory: 'भावना तथा संवेदी नियमन',
    ageRange: 'All Ages',
    nepaliAgeRange: 'सबै उमेर समूह',
    flutterRoute: '/emotion-regulation',
    shortDescription: 'Color-tiered emotional check-in system with guided grounding routines and sensory calming animations.',
    nepaliShortDescription: 'आफ्नो भावना पहिचान गरी शान्त हुन मद्दत गर्ने रङ र दृश्य संकेतहरू भएको डिजिटल बोर्ड।',
  },
  {
    _id: 'app-task-analysis',
    _type: 'supportiveWebApp',
    title: 'Daily Living Task Breakdown',
    nepaliTitle: 'दैनिक कार्य चरणबद्ध विश्लेषण',
    slug: { _type: 'slug', current: 'task-analysis' },
    order: 4,
    category: 'Executive Function & ADLs',
    nepaliCategory: 'दैनिक जीवन र आत्मनिर्भरता',
    ageRange: 'Ages 4–18+',
    nepaliAgeRange: '४–१८+ वर्ष',
    flutterRoute: '/task-analysis',
    shortDescription: 'Visual task checklists that deconstruct multi-step self-care and chores into manageable pictorial steps.',
    nepaliShortDescription: 'दाँत माझ्ने, लुगा लगाउने जस्ता जटिल कामहरूलाई साना-साना चरणहरूमा विभाजन गरी सिकाउने तालिका।',
  },
  {
    _id: 'app-visual-schedule',
    _type: 'supportiveWebApp',
    title: 'Daily Visual Routine Schedule',
    nepaliTitle: 'दैनिक दृश्य तालिका',
    slug: { _type: 'slug', current: 'visual-schedule' },
    order: 5,
    category: 'Executive Function & ADLs',
    nepaliCategory: 'दैनिक जीवन र आत्मनिर्भरता',
    ageRange: 'Ages 3–14+',
    nepaliAgeRange: '३–१४+ वर्ष',
    flutterRoute: '/visual-schedule',
    shortDescription: 'Predictable timeline board with draggable cards to ease transitions and reduce situational anxiety.',
    nepaliShortDescription: 'दिनभरको योजना स्पष्ट देखाएर बालबालिकाको डर र तनाव कम गर्ने दृश्य समय तालिका।',
  },
  {
    _id: 'app-social-stories',
    _type: 'supportiveWebApp',
    title: 'Interactive Social Scripts',
    nepaliTitle: 'सामाजिक कथाहरू र परिदृश्यहरू',
    slug: { _type: 'slug', current: 'social-stories' },
    order: 6,
    category: 'Social Understanding',
    nepaliCategory: 'सामाजिक बुझाइ तथा व्यवहार',
    ageRange: 'Ages 4–12+',
    nepaliAgeRange: '४–१२+ वर्ष',
    flutterRoute: '/social-stories',
    shortDescription: 'Clear, illustrated first-person social narratives explaining common social interactions and sensory situations.',
    nepaliShortDescription: 'नयाँ ठाउँ वा परिस्थितिमा कसरी प्रस्तुत हुने भन्ने कुरा सिकाउने सरल चित्रमय कथाहरू।',
  },
  {
    _id: 'app-first-then-board',
    _type: 'supportiveWebApp',
    title: 'First-Then Motivation Board',
    nepaliTitle: 'पहिले-त्यसपछि (First-Then) बोर्ड',
    slug: { _type: 'slug', current: 'first-then-board' },
    order: 7,
    category: 'Executive Function & ADLs',
    nepaliCategory: 'दैनिक जीवन र आत्मनिर्भरता',
    ageRange: 'Ages 2–10+',
    nepaliAgeRange: '२–१०+ वर्ष',
    flutterRoute: '/first-then-board',
    shortDescription: 'Premack-principle visual board framing non-preferred demands prior to high-interest sensory rewards.',
    nepaliShortDescription: 'पहिले गर्नुपर्ने काम र त्यसपछि पाइने मनपर्ने खेल स्पष्ट देखाएर काम पूरा गराउने बोर्ड।',
  },
  {
    _id: 'app-letter-tracing',
    _type: 'supportiveWebApp',
    title: 'Motor Precision Sensory Tracing',
    nepaliTitle: 'अक्षर ट्रेसिङ तथा मांसपेशी अभ्यास',
    slug: { _type: 'slug', current: 'letter-tracing' },
    order: 8,
    category: 'Motor & Writing Skills',
    nepaliCategory: 'लेखाइ तथा मांसपेशी समन्वय',
    ageRange: 'Ages 3–9+',
    nepaliAgeRange: '३–९+ वर्ष',
    flutterRoute: '/letter-tracing',
    shortDescription: 'High-tolerance visual tracing canvas supporting fine-motor coordination and early Nepali & English letter formation.',
    nepaliShortDescription: 'हातको मांसपेशी कमजोर भएका बालबालिकालाई अक्षर र आकार कोर्न सिकाउने संवेदी अभ्यास।',
  },

  // 4. Site Settings Singleton
  {
    _id: 'siteSettings',
    _type: 'siteSettings',
    siteName: 'Tech4Neurodivergent',
    siteTitle: 'Tech4Neurodivergent | Assistive Technology & Supportive Web-Apps',
    metaDescription: 'Open-access assistive technology platform and supportive web-apps engineered for autistic, Down syndrome, intellectual disability, and cerebral palsy learners.',
    heroBadge: 'Neurodevelopmental Assistive Technology Platform',
    nepaliHeroBadge: 'न्युरोडेभलपमेन्टल सहयोगी प्रविधि मञ्च',
    heroTitle: 'Evidence-Informed Assistive Technology & Supportive Web-Apps',
    nepaliHeroTitle: 'अटिजम, एडीएचडी र सिकाइ भिन्नता भएका बालबालिकाका लागि सहयोगी प्रविधि',
    heroSubtitle: 'Open-access, bilingual digital tools, visual scaffolding, and educational resources engineered to bypass communication barriers.',
    nepaliHeroSubtitle: 'नेपाली र अङ्ग्रेजी दुवै भाषामा उपलब्ध खुला, निःशुल्क डिजिटल उपकरण र शैक्षिक स्रोतहरू।',
    esewaId: '977 9841616976',
    esewaAccountName: 'Tech4Neurodivergent Community Fund',
    supportSubtitle: 'Help us maintain free edge hosting, Nepali speech synthesis, and open-source educational guides for families, educators, and neurodivergent learners.',
    nepaliSupportSubtitle: 'निःशुल्क होस्टिङ, नेपाली आवाज तथा खुला स्रोतका उपकरणहरू निरन्तर सञ्चालन गर्न सहयोग गर्नुहोस्।',
    disclaimerText: 'The software tools, visual roadmaps, and educational articles provided on tech4neurodivergent.com are designed exclusively for educational, supplemental, and communication-scaffolding purposes. They do not constitute formal medical diagnosis or clinical treatment.',
    nepaliDisclaimerText: 'यस वेबसाइटमा प्रस्तुत सामग्री तथा उपकरणहरू शैक्षिक र सञ्चार सहजीकरणका लागि मात्र हुन्। यी कुनै चिकित्सकीय उपचार वा औपचारिक निदान होइनन्।',
  },
];
